apiVersion: apps/v1
kind: Deployment
metadata:
  name: webuser-deployment
  labels:
    app: webuser
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webuser
  template:
    metadata:
      labels:
        app: webuser
    spec:
      containers:
      - name: webuser
        image: 15.164.129.57:8090/container-platform/container-platform-webuser:$BUILD_NUMBER
        imagePullPolicy: Always
        ports:
        - containerPort: 8091
        env:
        - name: K8S_IP
          value: "172.16.10.214"                                           
        - name: CONTAINER_PLATFORM_COMMON_API_URL
          value: "common-api-deployment.default.svc.cluster.local:3334"
        - name: CONTAINER_PLATFORM_API_URL
          value: "api-deployment.default.svc.cluster.local:3333"
        - name: REDIS_HOST
          value: "172.16.10.163"                                       
        - name: REDIS_PORT
          value: "32079"
        - name: REDIS_PASSWORD
          value: "password"
      imagePullSecrets:
        - name: jenkins-secret
      nodeSelector:
        kubernetes.io/hostname: paasta-cp-dev-cluster-2
---
apiVersion: v1
kind: Service
metadata:
  name: webuser-deployment
  labels:
    app: webuser
  namespace: default
spec:
  ports:
  - nodePort: 32091
    port: 8091
    protocol: TCP
    targetPort: 8091
  selector:
    app: webuser
  type: NodePort
