apiVersion: apps/v1
kind: Deployment
metadata:
  name: webuser-deployment
  labels:
    app: webuser
  namespace: cp-dev-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webuser
  template:
    metadata:
      labels:
        app: webuser
    spec:
      containers:
      - name: webuser
        image: $REGISTRY_HARBOR_URL/container-platform-new-dev/container-platform-webuser:$BUILD_NUMBER
        imagePullPolicy: Always
        ports:
        - containerPort: 2091
        env:
        - name: K8S_IP
          value: K8S_IP
        - name: CONTAINER_PLATFORM_COMMON_API_URL
          value: CONTAINER_PLATFORM_COMMON_API_URL
        - name: CONTAINER_PLATFORM_API_URL
          value: CONTAINER_PLATFORM_API_URL
      imagePullSecrets:
        - name: cp-dev-secret
---
apiVersion: v1
kind: Service
metadata:
  name: webuser-deployment
  labels:
    app: webuser
  namespace: cp-dev-namespace
spec:
  ports:
  - nodePort: 32702
    port: 2091
    protocol: TCP
    targetPort: 2091
  selector:
    app: webuser
  type: NodePort
